version: "3.9"

services:
  frontend:
    build:
      # Correction du nom (majuscules/minuscules selon ton dossier reel)
      context: ../FIARAHANTSIKA_DESKTOP
      dockerfile: Dockerfile
    image: arinomena/fiarahantsika-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      # Correction du nom (FiarahantsikaBackend sans underscore)
      context: ../FiarahantsikaBackend
      dockerfile: Dockerfile
    image: arinomena/fiarahantsika-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://fiarahantsikadev-nomena-feed.i.aivencloud.com:24502/defaultdb?useSSL=true
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_AiHQ0IOpIdcY-HGGyjZ
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  ml:
    build:
      context: ../Fiarahantsika_ML
      dockerfile: Dockerfile
    image: arinomena/fiarahantsika-ml:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=fiarahantsikadev-nomena-feed.i.aivencloud.com
      - DB_PORT=24502
      - DB_USER=avnadmin
      - DB_PASS=AVNS_AiHQ0IOpIdcY-HGGyjZ
      - DB_NAME=defaultdb
    restart: always